name: Compose Preview Screenshot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Build project and run screenshot tests
        working-directory: ./unit/BasicSample/
        run: ./gradlew assembleDebug

      - name: List APK files
        run: ls -R ./unit/BasicSample/app/build/outputs/apk/
      
      - name: Prepare output folder with build number
        working-directory: ./unit/BasicSample/
        id: prep_folder
        run: |
          mkdir -p ../../output/app-debug-${{ github.run_number }}
          cp ./app/build/outputs/apk/debug/app-debug.apk ../../output/app-debug-${{ github.run_number }}/
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.run_number }}
          path: output/app-debug-${{ github.run_number }}/app-debug.apk

      - name: Check copied APK
        run: ls -l output/app-debug-${{ github.run_number }}/
