name: Compose Preview Screenshot
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Build project and run screenshot tests
        working-directory: ./unit/BasicSample/
        run: ./gradlew assembleDebug

      - name: List APK files
        run: ls -R ./unit/BasicSample/app/build/outputs/apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BasicSample-debug-apk
          path: unit/BasicSample/app/build/outputs/apk/debug/app-debug.apk
